if(keyboard_check(ord("D"))){
	room_goto(rm_dino)	
}
if(keyboard_check(ord("C"))){
	room_goto(rm_cannonballs)	
}
if(keyboard_check(ord("R"))){
	game_restart()
}
if(keyboard_check(ord("P"))){
	room_goto(rm_painting)	
}